Fix ffmpeg version
The script compile ffmpeg from source version 5.1, however,
ffmpeg shows v1.38, which is this script's version information.

---- problem ----
$ ~/bin/ffmpeg -version
ffmpeg version v1.38 Copyright (c) 2000-2022 the FFmpeg developers

---- fix ----
$ ./workspace/bin/ffmpeg -version
ffmpeg version n5.1 Copyright (c) 2000-2022 the FFmpeg developers

---- reason ----
ffmpeg make file use git information to determine the version
information.
The ffmpeg tarball package doesn't contain git information,
resulting using this script's git info (v1.38) as its version
number.

---- solution ----
clone ffmpeg source with git info.

diff --git a/build-ffmpeg b/build-ffmpeg
--- a/build-ffmpeg
+++ b/build-ffmpeg
@@ -5,6 +5,8 @@
 
 PROGNAME=$(basename "$0")
 FFMPEG_VERSION=5.1
+FFMPEG_GIT_URL="https://git.ffmpeg.org/ffmpeg.git"
+FFMPEG_GIT_TAG=n${FFMPEG_VERSION}
 SCRIPT_VERSION=1.38
 CWD=$(pwd)
 PACKAGES="$CWD/packages"
@@ -112,6 +114,32 @@ download() {
   echo "Extracted $DOWNLOAD_FILE"
 
   cd "$DOWNLOAD_PATH/$TARGETDIR" || (
+    echo "Error has occurred."
+    exit 1
+  )
+}
+
+git_clone() {
+  # git_clone URL BRANCH DIRECTORY
+  local GIT_URL=$1
+  local GIT_BRANCH=$2
+  local DOWNLOAD_PATH=$3
+
+  if [[ ! -d "$DOWNLOAD_PATH" ]]; then
+    git clone -b ${GIT_BRANCH} --depath=1 ${GIT_URL} ${DOWNLOAD_PATH}
+
+    EXITCODE=$?
+    if [ $EXITCODE -ne 0 ]; then
+      echo ""
+      echo "Failed to clone $1. Exitcode $EXITCODE"
+      exit 1
+    fi
+
+  else
+    echo "$DOWNLOAD_PATH has already cloned."
+  fi
+
+  cd "$DOWNLOAD_PATH" || (
     echo "Error has occurred."
     exit 1
   )
@@ -917,7 +945,8 @@ if [[ "$OSTYPE" == "darwin"* ]]; then
 fi
 
 build "ffmpeg" "$FFMPEG_VERSION"
-download "https://github.com/FFmpeg/FFmpeg/archive/refs/heads/release/$FFMPEG_VERSION.tar.gz" "FFmpeg-release-$FFMPEG_VERSION.tar.gz"
+git_clone "${FFMPEG_GIT_URL}" "${FFMPEG_GIT_TAG}" "${PACKAGES}/FFmpeg-${FFMPEG_GIT_TAG}"
+
 # shellcheck disable=SC2086
 ./configure "${CONFIGURE_OPTIONS[@]}" \
   --disable-debug \
