add --skip-install and --auto-install options

diff --git a/build-ffmpeg b/build-ffmpeg
--- a/build-ffmpeg
+++ b/build-ffmpeg
@@ -237,6 +237,9 @@ usage() {
   echo "      --small                    Prioritize small size over speed and usability; don't build manpages"
   echo "      --full-static              Build a full static FFmpeg binary (eg. glibc, pthreads etc...) **only Linux**"
   echo "                                 Note: Because of the NSS (Name Service Switch), glibc does not recommend static links."
+  echo "      --skip-install             Don't install FFmpeg, FFprobe, and FFplay binaries to your system"
+  echo "      --auto-install             Install FFmpeg, FFprobe, and FFplay binaries to your system"
+  echo "                                 Note: Without --skip-install or --auto-install the script will prompt you to install."
   echo ""
 }
 
@@ -285,6 +288,20 @@ while (($# > 0)); do
     if [[ "$1" == "--small" ]]; then
       CONFIGURE_OPTIONS+=("--enable-small" "--disable-doc")
       MANPAGES=0
+    fi
+    if [[ "$1" == "--skip-install" ]]; then
+      SKIPINSTALL=yes
+      if [[ "$AUTOINSTALL" == "yes" ]]; then
+        echo "Error: The option --skip-install cannot be used with --auto-install"
+        exit 1
+      fi
+    fi
+    if [[ "$1" == "--auto-install" ]]; then
+      AUTOINSTALL=yes
+      if [[ "$SKIPINSTALL" == "yes" ]]; then
+        echo "Error: The option --auto-install cannot be used with --skip-install"
+        exit 1
+      fi
     fi
     shift
     ;;
