CPPFLAGS being set by libping could break libwebp build Moving flags being set outside if blocks build libtoolize for zimg remove old svt-av1 master tar files as it is not versioned Fix errant sudo command in AUTOINSTALL adding autoconf requirement for automake add m4 and automake build tools for libtool and zimg change AMF to use tar.gz and remove extra zip handling

diff --git a/build-ffmpeg b/build-ffmpeg
--- a/build-ffmpeg
+++ b/build-ffmpeg
@@ -91,22 +91,15 @@ download() {
 
   make_dir "$DOWNLOAD_PATH/$TARGETDIR"
 
-  if [[ $DOWNLOAD_FILE == *.zip ]]; then
-    if ! unzip "$DOWNLOAD_PATH/$DOWNLOAD_FILE" -d "$DOWNLOAD_PATH/$TARGETDIR" 2>/dev/null >/dev/null; then
-        echo "Failed to extract $DOWNLOAD_FILE";
-        exit 1;
+  if [ -n "$3" ]; then
+    if ! tar -xvf "$DOWNLOAD_PATH/$DOWNLOAD_FILE" -C "$DOWNLOAD_PATH/$TARGETDIR" 2>/dev/null >/dev/null; then
+      echo "Failed to extract $DOWNLOAD_FILE"
+      exit 1
     fi
   else
-    if [ -n "$3" ]; then
-      if ! tar -xvf "$DOWNLOAD_PATH/$DOWNLOAD_FILE" -C "$DOWNLOAD_PATH/$TARGETDIR" 2>/dev/null >/dev/null; then
-        echo "Failed to extract $DOWNLOAD_FILE"
-        exit 1
-      fi
-    else
-      if ! tar -xvf "$DOWNLOAD_PATH/$DOWNLOAD_FILE" -C "$DOWNLOAD_PATH/$TARGETDIR" --strip-components 1 2>/dev/null >/dev/null; then
-        echo "Failed to extract $DOWNLOAD_FILE"
-        exit 1
-      fi
+    if ! tar -xvf "$DOWNLOAD_PATH/$DOWNLOAD_FILE" -C "$DOWNLOAD_PATH/$TARGETDIR" --strip-components 1 2>/dev/null >/dev/null; then
+      echo "Failed to extract $DOWNLOAD_FILE"
+      exit 1
     fi
   fi
 
@@ -298,10 +291,6 @@ if ! command_exists "curl"; then
   exit 1
 fi
 
-if ! command_exists "libtoolize"; then
-  echo "libtool not installed. libzimg (z.lib) will not be available."
-fi
-
 if ! command_exists "cargo"; then
   echo "cargo not installed. rav1e will not be available."
 fi
@@ -382,9 +371,9 @@ if command_exists "python"; then
     execute ./waf configure --prefix="${WORKSPACE}" --static --no-shared --no-utils
     execute ./waf
     execute ./waf install
-    CFLAGS+=" -I$WORKSPACE/include/lilv-0"
     build_done "lilv" "0.24.12"
   fi
+  CFLAGS+=" -I$WORKSPACE/include/lilv-0"
 
   CONFIGURE_OPTIONS+=("--enable-lv2")
 fi
@@ -410,8 +399,40 @@ if build "zlib" "1.2.11"; then
   execute ./configure --static --prefix="${WORKSPACE}"
   execute make -j $MJOBS
   execute make install
-  LDFLAGS+=" -L/zlib/lib"
   build_done "zlib" "1.2.11"
+fi
+LDFLAGS+=" -L/zlib/lib"
+
+if build "m4" "1.4.19"; then
+  download "https://ftp.gnu.org/gnu/m4/m4-1.4.19.tar.gz"
+  execute ./configure --prefix="${WORKSPACE}"
+  execute make -j $MJOBS
+  execute make install
+  build_done "m4" "1.4.19"
+fi
+
+if build "autoconf" "2.71"; then
+  download "https://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.gz"
+  execute ./configure --prefix="${WORKSPACE}"
+  execute make -j $MJOBS
+  execute make install
+  build_done "autoconf" "2.71"
+fi
+
+if build "automake" "1.16.4"; then
+  download "https://ftp.gnu.org/gnu/automake/automake-1.16.4.tar.gz"
+  execute ./configure --prefix="${WORKSPACE}"
+  execute make -j $MJOBS
+  execute make install
+  build_done "automake" "1.16.4"
+fi
+
+if build "libtool" "2.4.6"; then
+  download "https://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz"
+  execute ./configure --prefix="${WORKSPACE}" --enable-static --disable-shared
+  execute make -j $MJOBS
+  execute make install
+  build_done "libtool" "2.4.6"
 fi
 
 if $NONFREE_AND_GPL; then
@@ -440,6 +461,7 @@ fi
 
 if ! $MACOS_M1; then
   if build "svtav1" $(date -I); then
+    execute rm -f "${PACKAGES}/SVT-AV1-master.tar.gz"
     download "https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/master/SVT-AV1-master.tar.gz"
     cd Build/linux || exit
     execute cmake -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DENABLE_SHARED=off -DBUILD_SHARED_LIBS=OFF ../.. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
@@ -667,6 +689,8 @@ if build "libpng" "1.6.37"; then
   execute make install
   build_done "libpng" "1.6.37"
 fi
+# libwebp can fail to compile on Ubuntu if these flags were left set to CFLAGS
+CPPFLAGS=
 
 ##
 ## image library
@@ -685,17 +709,18 @@ if build "libwebp" "1.2.0"; then
 fi
 CONFIGURE_OPTIONS+=("--enable-libwebp")
 
-if command_exists "libtoolize"; then
-  if build "zimg" "3.0.3"; then
-    download "https://github.com/sekrit-twc/zimg/archive/refs/tags/release-3.0.3.tar.gz"
-    execute ./autogen.sh
-    execute ./configure --prefix="${WORKSPACE}"
-    execute make -j $MJOBS
-    execute make install
-    build_done "zimg" "3.0.3"
-  fi
-  CONFIGURE_OPTIONS+=("--enable-libzimg")
+if build "zimg" "3.0.3"; then
+  download "https://github.com/sekrit-twc/zimg/archive/refs/tags/release-3.0.3.tar.gz" "zimg-3.0.3.tar.gz" "zimg"
+  cd zimg-release-3.0.3 || exit
+  execute ${WORKSPACE}/bin/libtoolize -i -f -q
+  execute ./autogen.sh --prefix="${WORKSPACE}"
+  execute ./configure --prefix="${WORKSPACE}" --enable-static --disable-shared
+  execute make -j $MJOBS
+  execute make install
+  build_done "zimg" "3.0.3"
 fi
+CONFIGURE_OPTIONS+=("--enable-libzimg")
+
 
 ##
 ## other library
@@ -763,18 +788,14 @@ if [[ "$OSTYPE" == "linux-gnu" ]]; then
     fi
   fi
 
-  # Only build AMF support if the amdgpu drivers are in use on the system
-  lspci -v | grep "Kernel driver in use: amdgpu" > /dev/null
-  if [ $? -eq 0 ]; then
-    if build "amf" "1.4.21.0"; then
-      download "https://github.com/GPUOpen-LibrariesAndSDKs/AMF/releases/download/v.1.4.21/AMF_SDK_1.4.21.0-2021-07-20.zip"
-      execute rm -rf ${WORKSPACE}/include/AMF
-      execute mkdir -p ${WORKSPACE}/include/AMF
-      execute cp -r ${PACKAGES}/AMF_SDK_1.4.21.0-2021-07-20/AMF_SDK_1.4.21.0/amf/public/include/* ${WORKSPACE}/include/AMF/
-      build_done "amf" "1.4.21.0"
-    fi
-    CONFIGURE_OPTIONS+=("--enable-amf")
+  if build "amf" "1.4.21.0"; then
+    download "https://github.com/GPUOpen-LibrariesAndSDKs/AMF/archive/refs/tags/v.1.4.21.tar.gz" "AMF-1.4.21.tar.gz" "AMF-1.4.21"
+    execute rm -rf ${WORKSPACE}/include/AMF
+    execute mkdir -p ${WORKSPACE}/include/AMF
+    execute cp -r ${PACKAGES}/AMF-1.4.21/AMF-v.1.4.21/amf/public/include/* ${WORKSPACE}/include/AMF/
+    build_done "amf" "1.4.21.0"
   fi
+  CONFIGURE_OPTIONS+=("--enable-amf")
 fi
 
 ##
@@ -827,7 +848,7 @@ if [[ "$AUTOINSTALL" == "yes" ]]; then
   else
     cp "$WORKSPACE/bin/ffmpeg" "$INSTALL_FOLDER/ffmpeg"
     cp "$WORKSPACE/bin/ffprobe" "$INSTALL_FOLDER/ffprobe"
-    sudo cp "$WORKSPACE/bin/ffplay" "$INSTALL_FOLDER/ffplay"
+    cp "$WORKSPACE/bin/ffplay" "$INSTALL_FOLDER/ffplay"
     echo "Done. FFmpeg is now installed to your system."
   fi
 elif [[ ! "$SKIPINSTALL" == "yes" ]]; then
