Fix & safety tweaks
- SC2086
- SC2145
- SC2126
+ MJobs Fix

ShellChecked for safety.

diff --git a/build-ffmpeg b/build-ffmpeg
--- a/build-ffmpeg
+++ b/build-ffmpeg
@@ -3,7 +3,7 @@
 # https://github.com/markus-perl/ffmpeg-build-script
 # Version 0.4
 
-CWD=`pwd`
+CWD=$(pwd)
 PACKAGES="$CWD/packages" 
 WORKSPACE="$CWD/workspace"
 CC=clang
@@ -13,9 +13,10 @@ PKG_CONFIG_PATH="${WORKSPACE}/lib/pkgconfig"
 
 # Speed up the process
 # Env Var NUMJOBS overrides automatic detection
+if [[ -n $NUMJOBS ]]; then
     MJOBS=$NUMJOBS
-elif [ -f /proc/cpuinfo ]; then
-    MJOBS=`grep processor /proc/cpuinfo | wc -l`
+elif [[ -f /proc/cpuinfo ]]; then
+    MJOBS=$(grep -c processor /proc/cpuinfo)
 else
     MJOBS=4
 fi
@@ -24,7 +25,7 @@ echo "Using $MJOBS make jobs simultaneously."
 make_dir () {
 	if [ ! -d $1 ]; then
 		if ! mkdir $1; then			
-			echo "\nFailed to create dir $1";
+			printf "\n Failed to create dir %s" "$1";
 			exit 1
 		fi
 	fi	
@@ -59,13 +60,13 @@ download () {
 }
 
 execute () {
-	echo "$ $@"
+	echo "$ $*"
 	OUTPUT="$($@ 2>&1)"
 	
 	if [ $? -ne 0 ]; then
-        echo $OUTPUT
+        echo "$OUTPUT"
         echo ""
-        echo "Failed to Execute $@" >&2
+        echo "Failed to Execute $*" >&2
         exit 1
     fi
 }
@@ -85,7 +86,7 @@ build () {
 }
 
 command_exists() {
-    if ! [ -x "$(command -v $1)" ]; then
+    if ! [[ -x $(command -v "$1") ]]; then
         return 1
     fi
 
@@ -134,8 +135,8 @@ fi
 
 if build "yasm"; then
 	download "http://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz" "yasm-1.3.0.tar.gz"
-	cd $PACKAGES/yasm-1.3.0
-	execute ./configure --prefix=${WORKSPACE} 
+	cd $PACKAGES/yasm-1.3.0 || exit
+	execute ./configure --prefix=${WORKSPACE}
 	execute make -j $MJOBS 
 	execute make install
 	build_done "yasm"
@@ -143,7 +144,7 @@ fi
 
 if build "opencore"; then
 	download "http://downloads.sourceforge.net/project/opencore-amr/opencore-amr/opencore-amr-0.1.3.tar.gz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fopencore-amr%2Ffiles%2Fopencore-amr%2F&ts=1442256558&use_mirror=netassist" "opencore-amr-0.1.3.tar.gz"
-	cd $PACKAGES/opencore-amr-0.1.3 
+	cd $PACKAGES/opencore-amr-0.1.3 || exit
 	execute ./configure --prefix=${WORKSPACE} --disable-shared --enable-static 
 	execute make -j $MJOBS
 	execute make install
@@ -152,7 +153,7 @@ fi
 
 if build "libvpx"; then
     download "https://github.com/webmproject/libvpx/archive/v1.5.0.tar.gz" "libvpx-1.5.0.tar.gz"
-    cd $PACKAGES/libvpx*
+    cd $PACKAGES/libvpx* || exit
 	sed   -e 's/cp -p/cp/' -i build/make/Makefile
 	execute ./configure --prefix=${WORKSPACE} --disable-unit-tests --disable-shared
 	execute make -j $MJOBS
@@ -162,7 +163,7 @@ fi
 
 if build "lame"; then
 	download "http://kent.dl.sourceforge.net/project/lame/lame/3.99/lame-3.99.5.tar.gz" "lame-3.99.5.tar.gz" 
-	cd $PACKAGES/lame-3.99.5
+	cd $PACKAGES/lame-3.99.5 || exit
 	execute ./configure --prefix=${WORKSPACE} --disable-shared --enable-static
 	execute make -j $MJOBS
 	execute make install
@@ -171,14 +172,14 @@ fi
 
 if build "xvidcore"; then
 	download "http://downloads.xvid.org/downloads/xvidcore-1.3.3.tar.gz" "xvidcore-1.3.3.tar.gz"
-	cd $PACKAGES/xvidcore 
-	cd build/generic 
+	cd $PACKAGES/xvidcore  || exit
+	cd build/generic  || exit
 	execute ./configure --prefix=${WORKSPACE} --disable-shared --enable-static
 	execute make -j $MJOBS
 	execute make install
 
-	if [ -f ${WORKSPACE}/lib/libxvidcore.4.dylib ]; then
-	    execute rm ${WORKSPACE}/lib/libxvidcore.4.dylib
+	if [[ -f ${WORKSPACE}/lib/libxvidcore.4.dylib ]]; then
+	    execute rm "${WORKSPACE}/lib/libxvidcore.4.dylib"
 	fi
 	
 	build_done "xvidcore"
@@ -186,7 +187,7 @@ fi
 
 if build "x264"; then
 	download "ftp://ftp.videolan.org/pub/x264/snapshots/last_x264.tar.bz2" "last_x264.tar.bz2"
-	cd $PACKAGES/x264-snapshot-* 
+	cd $PACKAGES/x264-snapshot-* || exit
 	execute ./configure --prefix=${WORKSPACE} --disable-shared --enable-static
 	execute make -j $MJOBS
 	execute make install
@@ -196,7 +197,7 @@ fi
 
 if build "libogg"; then
 	download "http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.gz" "libogg-1.3.2.tar.gz"
-	cd $PACKAGES/libogg-1.3.2
+	cd $PACKAGES/libogg-1.3.2 || exit
 	execute ./configure --prefix=${WORKSPACE} --disable-shared --enable-static
 	execute make -j $MJOBS
 	execute make install
@@ -205,7 +206,7 @@ fi
 
 if build "libvorbis"; then
 	download "http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.5.tar.gz" "libvorbis-1.3.5.tar.gz"
-	cd $PACKAGES/libvorbis-1.3.5
+	cd $PACKAGES/libvorbis-1.3.5 || exit
 	execute ./configure --prefix=${WORKSPACE} --with-ogg-libraries=${WORKSPACE}/lib --with-ogg-includes=${WORKSPACE}/include/ --enable-static --disable-shared --disable-oggtest
 	execute make -j $MJOBS
 	execute make install
@@ -214,7 +215,7 @@ fi
 
 if build "libtheora"; then
 	download "http://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.gz" "libtheora-1.1.1.tar.bz"
-	cd $PACKAGES/libtheora-1.1.1 
+	cd $PACKAGES/libtheora-1.1.1 || exit
 	sed "s/-fforce-addr//g" configure > configure.patched
 	chmod +x configure.patched
 	mv configure.patched configure
@@ -226,7 +227,7 @@ fi
 
 if build "pkg-config"; then
 	download "http://pkgconfig.freedesktop.org/releases/pkg-config-0.29.1.tar.gz" "pkg-config-0.29.1.tar.gz"
-	cd $PACKAGES/pkg-config-0.29.1
+	cd $PACKAGES/pkg-config-0.29.1 || exit
 	execute ./configure --silent --prefix=${WORKSPACE} --with-pc-path=${WORKSPACE}/lib/pkgconfig --with-internal-glib
 	execute make -j $MJOBS
 	execute make install
@@ -235,7 +236,7 @@ fi
 
 if build "cmake"; then
 	download "https://cmake.org/files/v3.5/cmake-3.5.0.tar.gz" "cmake-3.5.0.tar.gz"
-	cd $PACKAGES/cmake* 
+	cd $PACKAGES/cmake*  || exit
 	rm Modules/FindJava.cmake
 	perl -p -i -e "s/get_filename_component.JNIPATH/#get_filename_component(JNIPATH/g" Tests/CMakeLists.txt 
 	perl -p -i -e "s/get_filename_component.JNIPATH/#get_filename_component(JNIPATH/g" Tests/CMakeLists.txt 
@@ -247,7 +248,7 @@ fi
 
 if build "vid_stab"; then
 	download "https://codeload.github.com/georgmartius/vid.stab/legacy.tar.gz/release-0.98b" "vid.stab-0.98b-transcode-1.1-binary-x86_64.tgz"
-	cd $PACKAGES/georgmartius-vid*
+	cd $PACKAGES/georgmartius-vid* || exit
 	perl -p -i -e "s/vidstab SHARED/vidstab STATIC/" CMakeLists.txt 
 	execute cmake -DCMAKE_INSTALL_PREFIX:PATH=${WORKSPACE} . 
 	execute make -s install
@@ -256,8 +257,8 @@ fi
 
 if build "x265"; then
 	download "https://bitbucket.org/multicoreware/x265/downloads/x265_1.9.tar.gz" "x265-1.9.tar.gz"
-	cd $PACKAGES/x265_1.9
-	cd source
+	cd $PACKAGES/x265_1.9 || exit
+	cd source || exit
 	execute cmake -DCMAKE_INSTALL_PREFIX:PATH=${WORKSPACE} -DENABLE_SHARED:bool=off . 
 	execute make -j $MJOBS
 	execute make install
@@ -268,8 +269,7 @@ fi
 
 if build "fdk_aac"; then
 	download "http://downloads.sourceforge.net/project/opencore-amr/fdk-aac/fdk-aac-0.1.4.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fopencore-amr%2Ffiles%2Ffdk-aac%2F&ts=1457561564&use_mirror=kent" "fdk-aac-0.1.4.tar.gz"
-	
-	cd $PACKAGES/fdk-aac*
+	cd $PACKAGES/fdk-aac* || exit
 	execute ./configure --prefix=${WORKSPACE} --disable-shared --enable-static
 	execute make -j $MJOBS
 	execute make install
@@ -279,7 +279,7 @@ fi
 
 build "ffmpeg"
 download "http://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 " "ffmpeg-snapshot.tar.bz2 "
-cd $PACKAGES/ffmpeg*
+cd $PACKAGES/ffmpeg* || exit
 CFLAGS="-I$WORKSPACE/include" LDFLAGS="-L$WORKSPACE/lib" 
 execute ./configure  --arch=64 --prefix=${WORKSPACE} --extra-cflags="-I$WORKSPACE/include" --extra-ldflags="-L$WORKSPACE/lib" --extra-version=static --disable-debug --disable-shared --enable-static --extra-cflags=--static --disable-ffplay --disable-ffserver --disable-doc --enable-version3 --enable-libvpx --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-avfilter --enable-gpl --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-nonfree --enable-filters --enable-libvidstab --enable-libx265 --enable-runtime-cpudetect --enable-libfdk-aac
 execute make -j $MJOBS
